server:
  port: 9999

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.106.132.130:3306/ldg_compus?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  logging:
    file:  #日志文件名称
      name: log/springSchool.log
    level:
      root: info #日志级别 root表示所有包，也可以单独配置具体包 fatal error warn info debug trace off

  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1126458841@qq.com
    password: xxmtrivyiacwjgcd
    properties.mail.smtp.port: 465 #端口号465或587
    from: ldgloves@qq.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

  redis:
    host: 47.106.132.130
    database: 0
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: 2
        max-idle: 8

  rabbitmq:
    addresses: 47.106.132.130
    password: admin
    username: admin
    port: 5672
    virtual-host: /
    publisher-returns: true #消息发生到交换机，开启确认机制回调
    publisher-confirm-type: correlated  #消息发生到交换机，开启返回机制回调
    listener: #消费者
      simple:
        acknowledge-mode: manual
        concurrency: 4   #当前消费者的并行数量
        max-concurrency: 8   #当前消费者的最大的并行数量
        prefetch: 50      #每个消费者可以拉取多少个消息(未确认)
  aop:
    proxy-target-class: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

qiniu:
  accessKey: ZVwt4Sw_inv3AYkG7p0uXCilbCc2TJn4dWzjXRVv
  secretKey: m5gCEjfkKXVvidkSxK-nky6RYr69z0JNWspG48IW
  bucket: ldgschool3
  domain: r48kkavp6.hn-bkt.clouddn.com

